#!/usr/bin/perl
#
# count.pl
#

use strict;
use warnings;

my $char;
my %chars=();

print "AACAATGGGTGGTCAGCTACCATCCACCCAAGCGCGCAACGCATGTTGGTCAATCTTGTCGCCTAAAGTGGCATGTATTATGCGTGTCAAGCTTCCACTCTGACTTCTGAATGTCGTGATCATTCCGCTATAGACGACCGGCCGGCCGATGGACAACCTCGTTGGAGAAGGACTGACTGGCACTCTGCGCACAGGCCGAAAACCACGTTAACATGGGGACTACTACATTCTGTCGCGTTCCGAGCTACCACTTCAAAATCAAGCAGAACCTAGGGTTTTATCTAGTGTTCGGCCTACCACTTGGTTTTGGATCAATATTACGGTGCTGTGGACGTCAGCGGCCATGGGCGAGACAGAACAGAGCCCTGGCTTGTCATTTAGAGAAGTTAGTCCTCGACACCAACCGGAAGTTGCGCTCAGTCTAGATGACCGAAAGTGCGCACTACTTATAGGGTCACGAGTTCGACGAAATCCGTGCCCGTGGCCACACAACCTCACTGTTCTGTGAACACCCTGGAGGCTCCAGGCCGCGATTATAGTTTCCCGCTATACGAACGCTATGCGGTTTTCGGGCATTAAAGCGAGAAGTCACTTGTCTATCGAATTGATCAGAACGACTAGGTTACGCATCTGTCCCTGGATCCCGTGTGCGCGTCACGCCGGCAATCTTGGAGGCTTTCAAATAACACACTTGAACACATATGATATTCCTGGCACCTCCTACCCTTTCGGCGAGATCAGAGAGTATCACTGAGGCCATGTGAGGCTCTACAAGGAGAGACGTTGTAGTGAAGGCCGGCAATTAAATTTCAGTTTGGGGGAGGGAGCCAAGTACTAGTGGAATCCCTTCGGCACGGTCTGTTAGTGGACGCGGTCTAAGCCAGGGGCTAAACTCTCACGTAGACCTCCAACTTGATGACCATCTATATTCAGAGATTGCAGAGAACGGCAATGAAACTGTCTTACGGCGTTGGTATACTTTCT";

while( $char = getc() ) {
  last if( $char =~ /\n/ );
  $chars{ $char }++;
}

my @keys = sort keys( %chars );
foreach my $key (@keys) {
  print "$key = $chars{ $key }\n";
}